# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Documentation
    url: docs/
    weight: 20
  - name: API
    url: api/
    weight: 30
  - name: Showcase
    url: showcase/
    weight: 40
  - name: Community
    url: community/
    weight: 50

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: knowledge-hub
    name: "Knowledge Hub"
    pageRef: "knowledge-hub"
    weight: 2
  - identifier: discuss
    name: "Discuss"
    url: "https://github.com/sparklabOrg/codemetrica/discussions/categories/q-a"
    weight: 3
